### ISSUE TITLE
Erreur d'attribut avec le module parser

### ISSUE THREAD

**Issue by MyAlien** [Kr0wZ/SnapIntel#2]
Bonjour,
Quand j’exécute votre script Python j’obtiens cette erreur .

`PS D:\_Python\SnapIntel> python main.py -u magicneil -s
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    main()
  File "main.py", line 4, in main
    snap_dl = ssd.Snap_Story_Downloader()
  File "D:\_Python\SnapIntel\ssd.py", line 12, in __init__
    self.parser = parser.Parser()
AttributeError: module 'parser' has no attribute 'Parser'
PS D:\_Python\SnapIntel> `

Python version 3.8.10

**Comment by MyAlien** [comment]
ReBonjour,

Merci l'affichage est parfait ;)

Je vous remercie .

![Screen](https://github.com/Kr0wZ/SnapIntel/assets/43967214/730d9c8a-6f85-47c7-b574-aaab0e321f89)
